"""Bake a strategy vector into a self-contained submission file (main.py).

Usage: python make_main.py '[vec json]'   (default: SEED_VEC)
Writes main.py = farmlib.py source + `agent = build_agent(VEC)`, then verifies the
baked agent reproduces build_agent(VEC) exactly on two seeds vs pass.
"""
import sys, os, json
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from farmlib import SEED_VEC, build_agent


def main():
    vec = json.loads(sys.argv[1]) if len(sys.argv) > 1 else list(SEED_VEC)
    src = open(os.path.join(HERE, "farmlib.py")).read()
    header = ('"""Kaggriculture submission (sol4): animal-core + throttled multi-market farm.\n'
              "Generated by make_main.py from farmlib.py with a CEM-optimized strategy vector.\n"
              'See sol4/REPORT.md.\n"""\n')
    body = src.split('"""', 2)[2]  # drop farmlib's module docstring
    tail = f"\n\n# ---- baked strategy ---------------------------------------------------------\nVEC = {json.dumps(vec)}\nagent = build_agent(VEC)\n"
    out = os.path.join(HERE, "main.py")
    with open(out, "w") as fh:
        fh.write(header + body + tail)
    print(f"wrote {out} with VEC={vec}")

    # verify
    import importlib.util
    spec = importlib.util.spec_from_file_location("sol4main", out)
    mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
    from kaggle_environments import make
    for seed in (200, 201):
        r = []
        for ag in (mod.agent, build_agent(vec)):
            env = make("kaggriculture", configuration={"seed": seed}, debug=False)
            env.run([ag, "pass"])
            r.append(env.steps[-1][0]["reward"])
        print(f"seed {seed}: main={r[0]:.0f} farmlib={r[1]:.0f} match={abs(r[0]-r[1])<1e-6}")


if __name__ == "__main__":
    main()
