"""Bake the sol7 prototype (research/planner/{farmlib_ph,planner,planner_hung}.py) into a
single-file Kaggle submission main.py. Usage: python make_main.py
"""
import os, re
HERE = os.path.dirname(os.path.abspath(__file__))
PL = os.path.join(HERE, "research", "planner")

def strip_doc_and_imports(src, drop_imports):
    body = src.split('"""', 2)[2] if src.lstrip().startswith('"""') else src
    out = []
    for line in body.splitlines():
        if any(re.match(p, line) for p in drop_imports):
            continue
        out.append(line)
    return "\n".join(out)

fh = strip_doc_and_imports(open(os.path.join(PL, "farmlib_ph.py")).read(), [])
pl = strip_doc_and_imports(open(os.path.join(PL, "planner.py")).read(),
                           [r"^import os, sys, math$", r"^sys\.path\.insert", r"^import farmlib_p as F$"])
head = ('"""Kaggriculture submission (sol7): model-based daily production planner + Hungarian labor\n'
        "assignment + opponent-aware selling on sol5's mechanics layer. No tuned strategy vector.\n"
        'Generated by sol7/make_main.py. See sol7/RESEARCH.md and sol7/REPORT.md.\n"""\n')
bridge = ("\n\n# ---- namespace bridge: planner code refers to the mechanics layer as F ----------\n"
          "import types as _types\n"
          "F = _types.SimpleNamespace(**{k: v for k, v in dict(globals()).items() if not k.startswith('__')})\n"
          "import math\n")
tail = '''

# ---- entry point (from research/planner/planner_hung.py) ------------------------
def build_agent(verbose=False):
    P = F.vec_to_params(F.SEED_VEC)
    P["planner"] = True
    P["hands"] = lambda d: 8 if d >= LAST_DAY else (6 if d <= 3 else (9 if d <= 7 else 11))
    base = F.build_agent(P, hungarian=True)
    pl = Planner(P, base.mem, verbose=verbose)
    P["sell_override"] = pl.sell_override
    def agent(obs):
        pl.infer_flows(obs)
        if obs["day"] != pl.day:
            pl.day = obs["day"]
            pl.plan_day(obs)
        act = base(obs)
        pl.note_orders(act.get("market", []))
        return act
    agent.planner = pl; agent.stats = base.stats
    return agent


agent = build_agent()
'''
out = os.path.join(HERE, "main.py")
open(out, "w").write(head + fh + bridge + pl + tail)
print("wrote", out, os.path.getsize(out), "bytes")
