"""Bake the sol8 prototype (research/planner/{farmlib_ph,planner}.py) into a single-file
Kaggle submission main.py. Usage: python make_main.py
"""
import os, re
HERE = os.path.dirname(os.path.abspath(__file__))
PL = os.path.join(HERE, "research", "planner")


def strip_doc_and_imports(src, drop_imports):
    body = src.split('"""', 2)[2] if src.lstrip().startswith('"""') else src
    out = []
    for line in body.splitlines():
        if any(re.match(p, line) for p in drop_imports):
            continue
        out.append(line)
    return "\n".join(out)


fh = strip_doc_and_imports(open(os.path.join(PL, "farmlib_ph.py")).read(), [])
pl = strip_doc_and_imports(open(os.path.join(PL, "planner.py")).read(),
                           [r"^import os, sys, math$", r"^sys\.path\.insert", r"^import farmlib_ph as F$"])
head = ('"""Kaggriculture submission (sol8): graduated EMA-smoothed animal throttle (no hard\n'
        "culling) + contested-sink purchase floors + EMA-controlled reversible crop production\n"
        "+ geese/wheat idle-labor filler, on sol5's mechanics layer with Hungarian labor.\n"
        'Generated by sol8/make_main.py. See sol8/README.md and sol8/REPORT.md.\n"""\n')
bridge = ("\n\n# ---- namespace bridge: planner code refers to the mechanics layer as F ----------\n"
          "import types as _types\n"
          "F = _types.SimpleNamespace(**{k: v for k, v in dict(globals()).items() if not k.startswith('__')})\n"
          "import math\n")
tail = "\n\n# ---- entry point ----------------------------------------------------------------\nagent = build_agent()\n"
out = os.path.join(HERE, "main.py")
open(out, "w").write(head + fh + bridge + pl + tail)
print("wrote", out, os.path.getsize(out), "bytes")
